config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:  "homes#top"
  get 'home/about' =>'homes#about', as: 'about'

  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]

  resources :users, only:[:show, :index, :edit, :destroy, :update]



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

   validates :body, presence: true
   validates :title, presence: true
   validates :body, length: {maximum: 200}




end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :correct_user, only: [:edit, :update]
 before_action :authenticate_user!, except: [:login]
 def show
   @book = Book.find(params[:id])
   @user = @book.user
 end

 def new
   @book = Book.new
 end

 def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = @book.user
   if @book.save
       flash[:notice] = "Book was successfully created"
       redirect_to book_path(@book.id)
   else
      @books = Book.all
      render :index
   end
 end

 def index
    @book = Book.new
    @books = Book.all
    @user = current_user
 end

 def edit
  @book = Book.find(params[:id])
 end

 def update
    @book = Book.find(params[:id])
    if @book.update (book_params)
    redirect_to book_path, notice: 'Book information updated successfully'
    else
     if @book.update(book_params)
        redirect_to book_path(@book.id)
     else
    render :edit , status: :unprocessable_entity
    end
   end
 end

 def destroy
   @book = Book.find(params[:id])
   @book.destroy
   redirect_to books_path
 end

 private

 def book_params
  params.require(:book).permit(:title, :body)
 end

 def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
 end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
 <link rel="stylesheet" href="css/bootstrap.min.css">
 <script src="https://kit.fontawesome.com/30d49815c9.js" crossorigin="anonymous"></script>

<%= form_with(model: book, local: true) do |form| %>
<% if book.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h3>
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
       </ul>
  </div>
  </div>
  <% end %>
<% end %>

<div class="container">
   <div class="row">
      <div class="col-md-3">
<table class="table">

 <h3>User info</h3>
 <%= image_tag user.get_profile_image(100,100) %>

  <thead>
    <tr>
      <th scope="col">name</th>
      <th scope="col"><%= user.name %></th>
    </tr>
    <tr>
      <th style="border-bottom: none;">introduction</th>
      <th style="border-bottom: none;" scope="col"><%= user.introduction %></th>
    </tr>
  </thead>
    </table>

 
　　　　<%= link_to  edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do  %>
        <i class="fa fas fa-user-cog" style="color: gray;"></i>
　　　　<% end %>
　　　　
 

   <!--< % if user == current_user %>
<button type="button" class="btn btn-outline-secondary  btn-block">
  < %= link_to  edit_user_path(user), class: 'btn btn-default' do  %>
  <i class="fa fas fa-user-cog" style="color: gray;"></i>
  <span></span>
  </button>
 < % end %>
  < % end %-->


<%= form_with model: Book.new do |f| %>
<h3>New book</h3>

    <h4>title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>

    <div><%= f.submit 'Create Book', class: "btn btn-success" %></div>

<% end %>
</div>

app/views/books/edit.html.erb
<html>
<body>
  <div class="mx-auto" style="width: 200px;">

    <h2>Editing Book</h2>

      <%= form_with(model: @book, local: true) do |form| %>
      <% if @book.errors.any? %>
      <div id="error_explanation">
      <h3><%= pluralize(@book.errors.count, "error") %> prohibited book from being saved:</h3>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
      </div>
      <% end %>
      <% end %>

     <%= form_with model: @book do |f| %>
      <label for="inputName">Title</label>
      <div><%= f.text_field :title, autofocus: true, id:"BookName", placeholder:""%>
      <div><label for="inputIntroduction">Opinion</label>
      <div><%= f.text_area :body, autofocus: true, id:"caption",placeholder:""%>
      <div><%= f.submit "Update Book",class: "btn btn-success" %>
     <% end %>
     <div><%= link_to "Show" , book_path(@book) %>
     |
    <%= link_to "Back" , "/books" %>
    </div>
    </body>
    </html>

app/views/books/index.html.erb
<%= render 'list', user: @user, book: @book %>



   <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
  <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th style="width: 10%"></th>
      <th style="width: 30%">Title</th>
      <th>Opinion</th>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
      <%= link_to user_path(book.user.id) do %>
      <%= image_tag book.user.get_profile_image(100,100) %>
      <% end %>
      </td>

      <td>
         <%= link_to book_path(book.id) do %>
        <p><%= book.title %></p>
        <% end %>
      </td>
      <td><%= book.body %></td>
    </tr>
     <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<%= render 'list', user: @book.user, book: @book %>


  <div class="col-md-8 offset-md-1">
  <h3>Book detail</h3>
    <table class="table">
  <thead>

    <tr>
      <td scope="row">
       <%= image_tag @book.user.get_profile_image(100,100) %></br>
       <%= link_to @book.user.name, user_path(@user.id) %>
      </td>
      <td scope="row"><%= link_to @book.title %></td>
      <td scope="row"><%= @book.body %></td>
      <td scope="row">
          <% if @book.user == current_user %>
        <%= link_to "Edit", edit_book_path(@book.id) ,class: "btn btn-success" %>

      </td>
      <td scope="row">
        <%= link_to "Destroy", book_path(@book.id),class: "btn btn-sm btn-danger",method: :delete, "data-confirm" => "本当に削除しますか？" %>
        </button>
      <% end %>
</td>
    </tr>

  </thead>
  <tbody>
    <tr>
      <th scope="row"></th>
    </tr>
  </tbody>
</table>
</div>